name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure Git User Details
        run: |
          git config --global user.email "282142033+xucy10@users.noreply.github.com"
          git config --global user.name "Mili CI"

      - name: Apply All Patches
        run: ./gradlew applyAllPatches --no-configuration-cache

      - name: Restore Committed lmili-server/src/minecraft/
        run: |
          git checkout HEAD -- lmili-server/src/minecraft/

      - name: Publish to Maven Central
        run: ./gradlew :lmili-api:publish --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
